kind: Deployment
apiVersion: apps/v1
metadata:
  name: ft-ss
  labels:
    app.kubernetes.io/name: 'ft-ss'
    app.kubernetes.io/part-of: 'ft-ss'
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ft-ss
  template:
    metadata:
      labels:
        app.kubernetes.io/name: 'ft-ss'
        app.kubernetes.io/part-of: 'ft-ss'
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: 42screensaver
      containers:
      - name: ft-ss
        image: localhost:32000/42screensaver:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: "0.5"
            memory: 1Gi
        ports:
        - containerPort: 3000
        env:
        - name: API_UUID
          valueFrom:
            secretKeyRef:
              name: 42screensaver
              key: API_UUID
        - name: API_SECRET
          valueFrom:
            secretKeyRef:
              name: 42screensaver
              key: API_SECRET

---

kind: Service
apiVersion: v1
metadata:
  name: ft-ss
  labels:
    app.kubernetes.io/name: 'ft-ss'
    app.kubernetes.io/part-of: 'ft-ss'
spec:
  selector:
    app.kubernetes.io/name: ft-ss
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000

---

kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: http-ingress-ft-ss
  annotations:
    cert-manager.io/cluster-issuer: "lets-encrypt"
    kubernetes.io/ingress.class: "public"
    nginx.ingress.kubernetes.io/rewrite-target: '/$2'
  labels:
    app.kubernetes.io/part-of: 'ft-ss'
spec:
  tls:
  - hosts:
    - 42screensaver.alopez.fr
    secretName: ft-ss-tls
  rules:
  - host: 42screensaver.alopez.fr
    http:
      paths:
      - backend:
          service:
            name: ft-ss
            port:
              number: 80
        pathType: Prefix
        path: /()(.*)
